spring.application.name=ms-lacty

server.forward-headers-strategy=framework
# http://localhost:8082/ms-lacty/swagger-ui/index.html
# /ms-lacty/v3/api-docs

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.int[1,99]}


spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=rm558179
spring.datasource.password=fiap25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-3.6-flash

