spring.application.name=ms-gestor

server.forward-headers-strategy=framework
#http://localhost:8082/ms-gestor/swagger-ui/index.html
#/ms-gestor/v3/api-docs

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.int[1,99]}

# Configuração do Eureka Client (para ele se registrar no servidor 8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=rm558179
spring.datasource.password=fiap25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
